# Generated by Django 2.2.12 on 2022-07-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.CharField(max_length=30)),
                ('Name', models.CharField(max_length=30)),
                ('Category', models.CharField(max_length=30)),
                ('SubCategory', models.CharField(max_length=30)),
                ('Quantity', models.CharField(max_length=30)),
                ('Frequency', models.CharField(max_length=30)),
                ('Tags', models.CharField(max_length=30)),
                ('PurchaseDate', models.DateField()),
            ],
        ),
    ]
